import { Event, Attendee } from './types';

export const events: Event[] = [
  {
    id: '1',
    title: 'Tech Innovation Summit 2026',
    description: 'Join industry leaders for a day of insights on emerging technologies, AI, and digital transformation.',
    date: '2026-04-25',
    time: '09:00',
    location: 'San Francisco Convention Center',
    category: 'conference',
    capacity: 500,
    registered: 342,
    status: 'upcoming',
    organizer: 'TechCorp Events',
  },
  {
    id: '2',
    title: 'Advanced React Workshop',
    description: 'Deep dive into React performance optimization, state management patterns, and modern hooks.',
    date: '2026-04-18',
    time: '14:00',
    location: 'Innovation Hub, Building A',
    category: 'workshop',
    capacity: 50,
    registered: 48,
    status: 'upcoming',
    organizer: 'DevEducate',
  },
  {
    id: '3',
    title: 'Product Design Seminar',
    description: 'Learn design thinking methodologies and user-centered design principles from expert practitioners.',
    date: '2026-04-15',
    time: '10:00',
    location: 'Design Studio Co-working Space',
    category: 'seminar',
    capacity: 80,
    registered: 65,
    status: 'upcoming',
    organizer: 'Design Institute',
  },
  {
    id: '4',
    title: 'Startup Networking Mixer',
    description: 'Connect with founders, investors, and innovators in an evening of meaningful conversations.',
    date: '2026-04-20',
    time: '18:00',
    location: 'Skyline Rooftop Lounge',
    category: 'networking',
    capacity: 150,
    registered: 127,
    status: 'upcoming',
    organizer: 'Startup Community',
  },
  {
    id: '5',
    title: 'AI Ethics Webinar Series',
    description: 'Online discussion on responsible AI development, bias mitigation, and ethical frameworks.',
    date: '2026-04-22',
    time: '16:00',
    location: 'Virtual Event',
    category: 'webinar',
    capacity: 1000,
    registered: 543,
    status: 'upcoming',
    organizer: 'Ethics in Tech Foundation',
  },
  {
    id: '6',
    title: 'Annual Developer Conference',
    description: 'Three-day conference featuring keynotes, technical sessions, and hands-on labs.',
    date: '2026-03-28',
    time: '09:00',
    location: 'Metro Conference Complex',
    category: 'conference',
    capacity: 800,
    registered: 756,
    status: 'completed',
    organizer: 'DevCon Org',
  },
];

export const attendees: Attendee[] = [
  {
    id: 'a1',
    name: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    eventId: '1',
    registeredAt: '2026-03-15T10:30:00',
    status: 'confirmed',
  },
  {
    id: 'a2',
    name: 'Michael Chen',
    email: 'mchen@example.com',
    eventId: '1',
    registeredAt: '2026-03-16T14:20:00',
    status: 'confirmed',
  },
  {
    id: 'a3',
    name: 'Emily Rodriguez',
    email: 'emily.r@example.com',
    eventId: '2',
    registeredAt: '2026-03-20T09:15:00',
    status: 'confirmed',
  },
  {
    id: 'a4',
    name: 'David Kim',
    email: 'dkim@example.com',
    eventId: '2',
    registeredAt: '2026-03-21T16:45:00',
    status: 'pending',
  },
];
